sudo: required

language: php

services:
  - docker

install:
  - composer install
  - curl -LSs https://box-project.github.io/box2/installer.php | php

branches:
  only:
  - master
  - release

script:
  - ./box.phar build
  - docker build -t rdns:$TRAVIS_TAG .
