sudo: required

language: php
php:
  - 5.6

services:
  - docker

install:
  - composer install
  - curl -LSs https://box-project.github.io/box2/installer.php | php

branches:
  only:
  - master
  - release

script:
  - ./box.phar build
  - docker build . -t pwhelan/rdns:$TRAVIS_TAG
